name: pytorch_gpu
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=38.0.4
  - cuda=11.7.1
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-demo-suite=12.0.76
  - cuda-documentation=12.0.76
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.8.86
  - cuda-nsight-compute=12.0.0
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=12.0.76
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=12.0.90
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=12.0.90
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=12.0.90
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - flit-core=3.6.0
  - freetype=2.12.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcurand=10.3.1.50
  - libcurand-dev=10.3.1.50
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdeflate=1.8
  - libffi=3.4.2
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libpng=1.6.37
  - libtiff=4.5.0
  - libuv=1.40.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nsight-compute=2022.4.0.15
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1s
  - pillow=9.3.0
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.9
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - requests=2.28.1
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - torchaudio==0.13.1
      - torchvision==0.14.1
