name: tensorflow_gpu
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - libffi=3.4.2
  - openssl=1.1.1s
  - pip=22.3.1
  - python=3.10.9
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - tzdata=2022g
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cachetools==5.3.0
      - charset-normalizer==3.0.1
      - flatbuffers==23.1.21
      - gast==0.4.0
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.51.1
      - h5py==3.8.0
      - idna==3.4
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==15.0.6.1
      - markdown==3.4.1
      - markupsafe==2.1.2
      - numpy==1.24.1
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.0
      - protobuf==3.19.6
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - six==1.16.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-estimator==2.10.0
      - tensorflow-gpu==2.10.0
      - tensorflow-io-gcs-filesystem==0.30.0
      - termcolor==2.2.0
      - typing-extensions==4.4.0
      - urllib3==1.26.14
      - werkzeug==2.2.2
      - wrapt==1.14.1
